import type { AnalysisResult } from "./analysis-store";

export const demoAnalysis: AnalysisResult = {
  primary_witness: "Alan Bates",
  comparison_witnesses: ["Jo Hamilton", "Lee Castleton", "Seema Misra", "Paula Vennells"],
  total_claims: 8,
  trial_readiness: "MODERATE",
  trial_readiness_score: 0.62,
  gaps_count: 2,
  contradictions_count: 3,
  matrix: [
    {
      allegation_summary: "Horizon system produced unexplained shortfalls in branch accounts",
      allegation_type: "factual",
      topic: "horizon_defects",
      paragraph_ref: "¶12",
      witness_a: "Alan Bates",
      supporting: [
        { witness: "Jo Hamilton", passage: "My terminal showed a £2,000 shortfall overnight with no transactions.", paragraph: "¶8", confidence: "HIGH" },
        { witness: "Lee Castleton", passage: "Discrepancies appeared after every Horizon update.", paragraph: "¶15", confidence: "HIGH" },
        { witness: "Seema Misra", passage: "I could not reconcile the figures despite balancing nightly.", paragraph: "¶22", confidence: "MEDIUM" },
      ],
      contradicting: [],
      neutral: [],
      not_addressed: 0,
      gap: false,
      confidence: "HIGH",
    },
    {
      allegation_summary: "Post Office knew of Horizon bugs by 2010 and concealed them",
      allegation_type: "factual",
      topic: "concealment",
      paragraph_ref: "¶34",
      witness_a: "Alan Bates",
      supporting: [
        { witness: "Jo Hamilton", passage: "Helpline staff told me 'no one else has this problem' — I now know that was untrue.", paragraph: "¶19", confidence: "HIGH" },
      ],
      contradicting: [
        { witness: "Paula Vennells", passage: "I was not made aware of any systemic defects in Horizon at that time.", paragraph: "¶41", confidence: "HIGH", reasoning: "Direct denial of knowledge contradicts Bates' claim of institutional awareness." },
      ],
      neutral: ["Lee Castleton"],
      not_addressed: 1,
      gap: false,
      confidence: "MEDIUM",
    },
    {
      allegation_summary: "Sub-postmasters were contractually liable for shortfalls without audit rights",
      allegation_type: "legal",
      topic: "contracts",
      paragraph_ref: "¶47",
      witness_a: "Alan Bates",
      supporting: [
        { witness: "Lee Castleton", passage: "I was told to pay £25,000 with no opportunity to inspect the data.", paragraph: "¶29", confidence: "HIGH" },
        { witness: "Seema Misra", passage: "Refusal to pay led directly to prosecution.", paragraph: "¶38", confidence: "HIGH" },
      ],
      contradicting: [],
      neutral: [],
      not_addressed: 0,
      gap: false,
      confidence: "HIGH",
    },
    {
      allegation_summary: "Post Office investigators coerced confessions from sub-postmasters",
      allegation_type: "factual",
      topic: "investigations",
      paragraph_ref: "¶55",
      witness_a: "Alan Bates",
      supporting: [
        { witness: "Seema Misra", passage: "I was told if I signed, prosecution would be avoided.", paragraph: "¶44", confidence: "HIGH" },
      ],
      contradicting: [
        { witness: "Paula Vennells", passage: "Investigations followed proper procedure at all times.", paragraph: "¶52", confidence: "MEDIUM", reasoning: "Disputes the characterisation of investigator conduct." },
      ],
      neutral: [],
      not_addressed: 2,
      gap: false,
      confidence: "MEDIUM",
    },
    {
      allegation_summary: "Internal Fujitsu engineers could remotely alter branch transaction data",
      allegation_type: "technical",
      topic: "horizon_defects",
      paragraph_ref: "¶61",
      witness_a: "Alan Bates",
      supporting: [],
      contradicting: [],
      neutral: [],
      not_addressed: 4,
      gap: true,
      confidence: "LOW",
    },
    {
      allegation_summary: "Sub-postmasters received no meaningful Horizon training",
      allegation_type: "factual",
      topic: "training",
      paragraph_ref: "¶68",
      witness_a: "Alan Bates",
      supporting: [
        { witness: "Jo Hamilton", passage: "Two days of training, then I was on my own.", paragraph: "¶26", confidence: "HIGH" },
      ],
      contradicting: [
        { witness: "Paula Vennells", passage: "All sub-postmasters received comprehensive onboarding.", paragraph: "¶60", confidence: "MEDIUM", reasoning: "Conflicts with witness accounts of inadequate preparation." },
      ],
      neutral: ["Lee Castleton", "Seema Misra"],
      not_addressed: 0,
      gap: false,
      confidence: "MEDIUM",
    },
    {
      allegation_summary: "Post Office pursued private prosecutions to recover disputed sums",
      allegation_type: "legal",
      topic: "prosecutions",
      paragraph_ref: "¶74",
      witness_a: "Alan Bates",
      supporting: [
        { witness: "Seema Misra", passage: "I was prosecuted and imprisoned while pregnant.", paragraph: "¶51", confidence: "HIGH" },
        { witness: "Lee Castleton", passage: "Civil action bankrupted me.", paragraph: "¶33", confidence: "HIGH" },
      ],
      contradicting: [],
      neutral: [],
      not_addressed: 0,
      gap: false,
      confidence: "HIGH",
    },
    {
      allegation_summary: "Post Office board received regular reports on Horizon-related disputes",
      allegation_type: "factual",
      topic: "governance",
      paragraph_ref: "¶82",
      witness_a: "Alan Bates",
      supporting: [],
      contradicting: [],
      neutral: [],
      not_addressed: 4,
      gap: true,
      confidence: "LOW",
    },
  ],
  gaps: [
    { allegation_summary: "Internal Fujitsu engineers could remotely alter branch transaction data", topic: "horizon_defects", paragraph_ref: "¶61" },
    { allegation_summary: "Post Office board received regular reports on Horizon-related disputes", topic: "governance", paragraph_ref: "¶82" },
  ],
  contradictions: [
    {
      allegation_summary: "Post Office knew of Horizon bugs by 2010 and concealed them",
      topic: "concealment",
      contradicting: [
        { witness: "Paula Vennells", passage: "I was not made aware of any systemic defects in Horizon at that time.", paragraph: "¶41", confidence: "HIGH", reasoning: "Direct denial of knowledge contradicts Bates' claim of institutional awareness." },
      ],
    },
    {
      allegation_summary: "Post Office investigators coerced confessions from sub-postmasters",
      topic: "investigations",
      contradicting: [
        { witness: "Paula Vennells", passage: "Investigations followed proper procedure at all times.", paragraph: "¶52", confidence: "MEDIUM", reasoning: "Disputes the characterisation of investigator conduct." },
      ],
    },
    {
      allegation_summary: "Sub-postmasters received no meaningful Horizon training",
      topic: "training",
      contradicting: [
        { witness: "Paula Vennells", passage: "All sub-postmasters received comprehensive onboarding.", paragraph: "¶60", confidence: "MEDIUM", reasoning: "Conflicts with witness accounts of inadequate preparation." },
      ],
    },
  ],
};
