/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as EvidenceMatrixRouteImport } from './routes/evidence-matrix'
import { Route as BoardRouteImport } from './routes/board'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvidenceMatrixDocumentExhibitRouteImport } from './routes/evidence-matrix.document.$exhibit'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceMatrixRoute = EvidenceMatrixRouteImport.update({
  id: '/evidence-matrix',
  path: '/evidence-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceMatrixDocumentExhibitRoute =
  EvidenceMatrixDocumentExhibitRouteImport.update({
    id: '/document/$exhibit',
    path: '/document/$exhibit',
    getParentRoute: () => EvidenceMatrixRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/evidence-matrix': typeof EvidenceMatrixRouteWithChildren
  '/matrix': typeof MatrixRoute
  '/report': typeof ReportRoute
  '/evidence-matrix/document/$exhibit': typeof EvidenceMatrixDocumentExhibitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/evidence-matrix': typeof EvidenceMatrixRouteWithChildren
  '/matrix': typeof MatrixRoute
  '/report': typeof ReportRoute
  '/evidence-matrix/document/$exhibit': typeof EvidenceMatrixDocumentExhibitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/board': typeof BoardRoute
  '/evidence-matrix': typeof EvidenceMatrixRouteWithChildren
  '/matrix': typeof MatrixRoute
  '/report': typeof ReportRoute
  '/evidence-matrix/document/$exhibit': typeof EvidenceMatrixDocumentExhibitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/board'
    | '/evidence-matrix'
    | '/matrix'
    | '/report'
    | '/evidence-matrix/document/$exhibit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/board'
    | '/evidence-matrix'
    | '/matrix'
    | '/report'
    | '/evidence-matrix/document/$exhibit'
  id:
    | '__root__'
    | '/'
    | '/board'
    | '/evidence-matrix'
    | '/matrix'
    | '/report'
    | '/evidence-matrix/document/$exhibit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardRoute: typeof BoardRoute
  EvidenceMatrixRoute: typeof EvidenceMatrixRouteWithChildren
  MatrixRoute: typeof MatrixRoute
  ReportRoute: typeof ReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence-matrix': {
      id: '/evidence-matrix'
      path: '/evidence-matrix'
      fullPath: '/evidence-matrix'
      preLoaderRoute: typeof EvidenceMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence-matrix/document/$exhibit': {
      id: '/evidence-matrix/document/$exhibit'
      path: '/document/$exhibit'
      fullPath: '/evidence-matrix/document/$exhibit'
      preLoaderRoute: typeof EvidenceMatrixDocumentExhibitRouteImport
      parentRoute: typeof EvidenceMatrixRoute
    }
  }
}

interface EvidenceMatrixRouteChildren {
  EvidenceMatrixDocumentExhibitRoute: typeof EvidenceMatrixDocumentExhibitRoute
}

const EvidenceMatrixRouteChildren: EvidenceMatrixRouteChildren = {
  EvidenceMatrixDocumentExhibitRoute: EvidenceMatrixDocumentExhibitRoute,
}

const EvidenceMatrixRouteWithChildren = EvidenceMatrixRoute._addFileChildren(
  EvidenceMatrixRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardRoute: BoardRoute,
  EvidenceMatrixRoute: EvidenceMatrixRouteWithChildren,
  MatrixRoute: MatrixRoute,
  ReportRoute: ReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
